name: Build website for learning about the current VUMC medicine residents

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Checkout res-db
      uses: actions/checkout@v2
      with:
        repository: cbeauhilton/vumc-resident-map-db
        path: vumc-resident-map-db
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sqlite-utils
        datasette install datasette-publish-vercel
    - name: Build database
      run: |-
        python map.py
        sqlite-utils insert vumc2022.db residents bio_map.csv --csv
    - name: save db to cbeauhilton/vumc-resident-map-db
      run: |-
        cd vumc-resident-map-db
        git config --global user.email "db-bot@example.com"
        git config --global user.name "db-bot"       
        cp ../vumc2022.db .
        cp ../bio_map.csv .
        git add *.db
        git add *.csv
        git commit --amend --no-edit
        git push --force
    - name: deploy
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish vercel vumc2022.db \
          --setting default_page_size 300 \
          --token $NOW_TOKEN \
          --project vumc-resident-map \
          --static static:static \
          --install datasette-json-html \
          --install datasette-cluster-map \
          --public
