name: Build website for learning about the current VUMC medicine residents

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Checkout res-db
      uses: actions/checkout@v2
      with:
        repository: cbeauhilton/vumc-resident-map-db
        path: vumc-resident-map-db
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Node.js
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
    # - uses: actions/cache@v2
    #   name: Configure npm caching
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-node-
    #     restore-keys: |
    #       ${{ runner.os }}-node-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install datasette-publish-vercel
        pip install sqlite-utils
    - name: Install npm dependencies
      run: sudo npm install -g puppeteer-cli --unsafe-perm=true
    - name: Set up dirs
      run: |
        mkdir -p data
    # - name: Download previous database unless REBUILD in commit message
    #   if: |-
    #     !contains(github.event.head_commit.message, 'REBUILD')
    #   run: curl --fail -o data/residents.db https://raw.githubusercontent.com/cbeauhilton/vumc-resident-map-db/main/residents.db
    #   continue-on-error: true
    - name: Build database
      run: |-
        python scrape.py && python map.py
    - name: Soundness check
      run: |-
        cd data
        datasette . --get / | grep "residents"
    - name: Save residents.db to cbeauhilton/vumc-resident-map-db
      run: |-
        cd vumc-resident-map-db
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"       
        cp ../data/residents.db .
        git add residents.db
        git commit --amend --no-edit
        git push --force
    - name: Deploy Datasette using Vercel
      env:
        NOW_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel data/residents.db \
          --setting default_page_size 300 \
          --token $NOW_TOKEN \
          --branch main \
          --project vumc-resident-map \
          --install datasette-json-html \
          --install datasette-cluster-map \
          --public
